spring:
  application:
    name: aufgabe1

  datasource:
    url: jdbc:mysql://192.168.29.128:3306/m295
    username: tech_user
    password: admin12345

  profiles:
    active: development

  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

ad:
  domain: atbs21.atb
  url: ldap://192.168.29.50:389
  root-dn: DC=atbs21,DC=atb